services:
  cesium-api:
    build:
      additional_contexts:
        dist: ../dist
      args:
        VERSION: RE_VERSION
      tags:
        - uniclogs/cesium-backend:latest
        - uniclogs/cesium-backend:RE_VERSION

    image: cesium-backend:RE_VERSION
    ports:
      - '9000:9000'
    volumes:
      - globe_data:/var/cesium-api/

volumes:
  globe_data: