services:
  cesium-api:
    build:
      additional_contexts:
        dist: ../dist
      args:
        VERSION: RE_VERSION
      tags:
        - oresat/cesium-backend:latest
        - oresat/cesium-backend:RE_VERSION

    image: oresat/cesium-backend:latest
    environment:
      API_HOST: 0.0.0.0
      API_PORT: 6008
    ports:
      - 6008:6008
    volumes:
      - globe_data:/var/cesium-api/

volumes:
  globe_data:
