name: Pull Request CI Actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.14t"

jobs:
  ci_setup:
    runs-on: ubuntu-slim

    steps:
      - &checkout
        name: Checkout Repo
        uses: actions/checkout@v7

      - &setup_python
        name: Set-Up Python v${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install Dependencies
        run: pip install .[ci]

  linting:
    runs-on: ubuntu-slim
    needs: [ci_setup]
    steps:
      - *checkout
      - *setup_python

      - name: Debug
        run: pip freeze

      # - name: Check Linting
      #   run: python -m ruff check

  # formatting:
  #   runs-on: ubuntu-slim
  #   needs: [ci_setup]
  #   steps:
  #     - *checkout
  #     - *fetch_python

  #     - name: Check Formatting
  #       run: python -m ruff format --check

  # unit-tests:
  #   runs-on: ubuntu-slim
  #   needs: [ci_setup]
  #   steps:
  #     - *checkout
  #     - *fetch_python

  #     - name: Run Unit Tests
  #       run: python -m pytest
